### ISSUE TITLE
Address minor nits from GoLang CI Report

### ISSUE THREAD

**Issue by seanprashad** [mdanzinger/whatsapptistics#5]
https://golangci.com/r/github.com/mdanzinger/whatsapptistics

![image](https://user-images.githubusercontent.com/13009507/49324841-3274f480-f504-11e8-8a82-0c9adf6c0a3a.png)

**Comment by mdanzinger** [comment]
@SeanPrashad Thanks for reporting this and for the previous pull request! I should be tackling these in my next few commits.
