### ISSUE TITLE
Make all depedencies configurable

### ISSUE THREAD

**Issue by mdanzinger** [mdanzinger/whatsapptistics#6]
Most dependencies currently have values hard-coded ([s3 storage for example).](https://github.com/mdanzinger/whatsapptistics/blob/6a893fee3c004e75c9f153edc72d3cded87d587b/store/s3/chat_repo.go#L24) We should be parsing a `config.json` (or YAML, etc) file in `main.go`, and passing them into the constructors accordingly.

**Comment by biskit1** [comment]
What do you think about loading environment variables from a dotenv file?

**Comment by mdanzinger** [comment]
@biskit1 That'd definitely be better than the current hard-coded values! PR incoming?

**Comment by biskit1** [comment]
@mdanzinger  yup! Ready for your review 👍 
Did you still want to eventually explore other methods like the ones you first mentioned? If that's the case, then maybe keep this issue open?

**Comment by mdanzinger** [comment]
`.env` is a good solution for now!
